### ISSUE TITLE
NSString+WTSafe中的私有类审核被拒问题

### ISSUE THREAD

**Issue by dabing1022** [hongruqi/SafeGuard#1]
NSString+WTSafe类中有大量的私有类，这样的审核风险很大吧。https://juejin.im/user/597a9a1f5188253de3721032 掘金上也有人反馈因为私有类被拒的问题，所以想问作者是否将代码运用到了线上？

**Comment by hongruqi** [comment]
hi ChildhoodAndy:
可以放心使用，我们线上产品已经使用两个月，7，8个版本。未出现审核不过问题。
以上
walter





在 2017-10-30 18:14:58，"ChildhoodAndy" <notifications@github.com> 写道：


NSString+WTSafe类中有大量的私有累，这样的审核风险很大吧。https://juejin.im/user/597a9a1f5188253de3721032 掘金上也有人反馈因为私有类被拒的问题，所以想问作者是否将代码运用到了线上？
